/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSuggestionsRouteImport } from './routes/app.suggestions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppComplaintsRouteImport } from './routes/app.complaints'
import { Route as AppComplaintsIdRouteImport } from './routes/app.complaints.$id'

const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuggestionsRoute = AppSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIdRoute = AppComplaintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppComplaintsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/role-select': typeof RoleSelectRoute
  '/app/complaints': typeof AppComplaintsRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app/users': typeof AppUsersRoute
  '/app/complaints/$id': typeof AppComplaintsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/role-select': typeof RoleSelectRoute
  '/app/complaints': typeof AppComplaintsRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app/users': typeof AppUsersRoute
  '/app/complaints/$id': typeof AppComplaintsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/role-select': typeof RoleSelectRoute
  '/app/complaints': typeof AppComplaintsRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app/users': typeof AppUsersRoute
  '/app/complaints/$id': typeof AppComplaintsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/pending'
    | '/role-select'
    | '/app/complaints'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/suggestions'
    | '/app/users'
    | '/app/complaints/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/pending'
    | '/role-select'
    | '/app/complaints'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/suggestions'
    | '/app/users'
    | '/app/complaints/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/pending'
    | '/role-select'
    | '/app/complaints'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/suggestions'
    | '/app/users'
    | '/app/complaints/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  RoleSelectRoute: typeof RoleSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suggestions': {
      id: '/app/suggestions'
      path: '/suggestions'
      fullPath: '/app/suggestions'
      preLoaderRoute: typeof AppSuggestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/complaints': {
      id: '/app/complaints'
      path: '/complaints'
      fullPath: '/app/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/complaints/$id': {
      id: '/app/complaints/$id'
      path: '/$id'
      fullPath: '/app/complaints/$id'
      preLoaderRoute: typeof AppComplaintsIdRouteImport
      parentRoute: typeof AppComplaintsRoute
    }
  }
}

interface AppComplaintsRouteChildren {
  AppComplaintsIdRoute: typeof AppComplaintsIdRoute
}

const AppComplaintsRouteChildren: AppComplaintsRouteChildren = {
  AppComplaintsIdRoute: AppComplaintsIdRoute,
}

const AppComplaintsRouteWithChildren = AppComplaintsRoute._addFileChildren(
  AppComplaintsRouteChildren,
)

interface AppRouteChildren {
  AppComplaintsRoute: typeof AppComplaintsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSuggestionsRoute: typeof AppSuggestionsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComplaintsRoute: AppComplaintsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSuggestionsRoute: AppSuggestionsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  RoleSelectRoute: RoleSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
